#!/bin/bash
# SessionStart hook for Claude Code on the web.
#
# Installs what the dev/ test suites need so the offline-capable GitHub CI lanes
# (.github/workflows/node.js.yml) also run here in a remote session:
#   npm test                    (unit)              -> dev/ node_modules              [offline OK]
#   npm run test:rules          (firestore rules)   -> firebase-tools + JVM emulator  [offline OK]
#   npm run test:storage-rules  (storage rules)     -> firebase-tools + JVM emulator  [offline OK]
#   npm run test:ui             (Playwright UI)     -> Chromium + /vendor assets      [offline OK]
#   npm run test:e2e-firebase   (Playwright + emu)  -> Firebase JS SDK from gstatic   [needs CDN]
#   npm run test:cdn            (CDN SRI fallback)  -> outbound to jsdelivr           [needs CDN]
#
# The last two reach external CDNs the container's network policy blocks — run them in GitHub CI.
# Chromium and Java are already provisioned in the web container, so this hook adds: the npm
# dependencies, the Firebase CLI + emulator JARs, and the vendored Vue/Vuetify/MDI dists the
# Playwright suites serve from /vendor.
set -euo pipefail

# Only do work in the remote (web) container; local machines set themselves up.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
DEV_DIR="$ROOT/dev"

# 1. Dev dependencies for the unit suite + Playwright runner (better-sqlite3,
#    @playwright/test, firebase, @firebase/rules-unit-testing). `npm install`
#    (not `npm ci`) so the post-hook container cache is reused on later runs.
echo "[session-start] installing dev/ npm dependencies..."
npm install --prefix "$DEV_DIR"

# 2. Firebase CLI — the rules, storage-rules and firebase-mode E2E suites drive
#    the Firestore/Storage emulators through it. Skip the reinstall if present.
if ! command -v firebase >/dev/null 2>&1; then
  echo "[session-start] installing firebase-tools globally..."
  npm install -g firebase-tools
else
  echo "[session-start] firebase-tools already present ($(firebase --version | head -1))"
fi

# 2b. Pre-download the emulator JARs (Firestore + Storage rules runtime) now, while the proxy still
#     has egress. run-with-emulators.mjs runs the emulators with the proxy stripped (it breaks the
#     Storage->Firestore cross-service call), so the JARs must already be cached by test time.
if [ ! -d "$HOME/.cache/firebase/emulators" ] || [ -z "$(ls -A "$HOME/.cache/firebase/emulators" 2>/dev/null)" ]; then
  echo "[session-start] pre-downloading Firebase emulator JARs..."
  firebase setup:emulators:firestore >/dev/null 2>&1 || echo "[session-start] warn: firestore emulator prefetch failed (will download on first run)"
  firebase setup:emulators:storage   >/dev/null 2>&1 || echo "[session-start] warn: storage emulator prefetch failed (will download on first run)"
else
  echo "[session-start] emulator JARs already cached."
fi

# 3. Vendored front-end dists the Playwright suites serve from /vendor.
#    The app loads /vendor/{vue,vuetify}.js first and only falls back to the
#    jsdelivr CDN if that 404s. These dists are not committed, and the web
#    container's network policy blocks jsdelivr, so without them the app can't
#    boot and every UI/E2E test fails. update-vendor.sh pulls from jsdelivr
#    (blocked here); instead we materialise the exact same pinned files from the
#    npm registry, which the container's proxy DOES allow. Idempotent: skips if
#    the dists are already in place.
if [ ! -f "$ROOT/vendor/vue.js" ]; then
  echo "[session-start] fetching vendored Vue/Vuetify/MDI dists from npm..."
  # shellcheck disable=SC1091
  source "$ROOT/vendor/versions"   # VUE, VUETIFY, MDI
  tmp="$(mktemp -d)"
  (
    cd "$tmp"
    npm pack "vue@${VUE}" "vuetify@${VUETIFY}" "@mdi/font@${MDI}" >/dev/null 2>&1
    for f in *.tgz; do tar xzf "$f"; mv package "${f%.tgz}"; done
  )
  mkdir -p "$ROOT/vendor/fonts"
  cp "$tmp/vue-${VUE}/dist/vue.global.prod.js"                       "$ROOT/vendor/vue.js"
  cp "$tmp/vuetify-${VUETIFY}/dist/vuetify.min.js"                   "$ROOT/vendor/vuetify.js"
  cp "$tmp/vuetify-${VUETIFY}/dist/vuetify.min.css"                  "$ROOT/vendor/vuetify.css"
  cp "$tmp/mdi-font-${MDI}/css/materialdesignicons.min.css"         "$ROOT/vendor/mdi.css"
  cp "$tmp/mdi-font-${MDI}/fonts/materialdesignicons-webfont.woff2" "$ROOT/vendor/fonts/materialdesignicons-webfont.woff2"
  # The npm mdi css lives under css/ and points at ../fonts/. We flatten it to /vendor/mdi.css, so
  # rewrite the font ref to ./fonts/ — otherwise ../fonts/ resolves to /fonts/ (404) and the icon glyphs
  # never load. (This container copy is untracked; the committed /vendor is regenerated by update-vendor.sh.)
  sed -i 's#\.\./fonts/#./fonts/#g' "$ROOT/vendor/mdi.css"
  rm -rf "$tmp"
  echo "[session-start] vendor/ populated (Vue ${VUE}, Vuetify ${VUETIFY}, MDI ${MDI})."
else
  echo "[session-start] vendor dists already present."
fi

echo "[session-start] done. Offline-capable suites (run from dev/): npm test, test:rules, test:storage-rules, test:ui."
echo "[session-start] note: test:e2e-firebase (Firebase JS SDK from gstatic) and test:cdn (jsdelivr integrity)"
echo "[session-start]       reach external CDNs the web container's network policy blocks — run those in GitHub CI."
